all:
  vars:
    ip_master: 192.168.1.180
  children:
    master:
      hosts:
        pi-00:
          ansible_host: 192.168.1.180
          ansible_python_interpreter: /usr/bin/python3
    nodes:
      hosts:
        pi-01:
          ansible_host: 192.168.1.181
          ansible_python_interpreter: /usr/bin/python3
        pi-02:
          ansible_host: 192.168.1.182
          ansible_python_interpreter: /usr/bin/python3
        pi-03:
          ansible_host: 192.168.1.183
          ansible_python_interpreter: /usr/bin/python3
        pi-04:
          ansible_host: 192.168.1.184
          ansible_python_interpreter: /usr/bin/python3
        pi-05:
          ansible_host: 192.168.1.185
          ansible_python_interpreter: /usr/bin/python3
        pi-06:
          ansible_host: 192.168.1.186
          ansible_python_interpreter: /usr/bin/python3
        pi-07:
          ansible_host: 192.168.1.187
          ansible_python_interpreter: /usr/bin/python3
        pi-08:
          ansible_host: 192.168.1.188
          ansible_python_interpreter: /usr/bin/python3


