
- name: ajout du hostname dans /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"

- name: append cgroup mem settings in /boot/cmdline.txt
  lineinfile:
    path: "/boot/cmdline.txt"
    backrefs: yes
    regexp: "^(.*rootwait.*)$"
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'

- name: désactivation du swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True

- name: swapoff
  shell: swapoff -a
